services:
  python:
    build: .
    container_name: python-server
    ports:
      - 8000:8000
    volumes:
      - ./Backend:/code
  
  mysqldb:
    image: mysql
    container_name: mysqldb-server
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password-123
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

  frontend:
    image: nginx:latest
    container_name: frontend-server
    ports:
      - "8080:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html

volumes:
  mysql:
  mysql_config: